### ISSUE TITLE
TimeZone of UTC+5:30

### ISSUE THREAD

**Issue by sshikalgar** [Kotlin/kotlinx-datetime#102] opened 2021-03-12 06:26 UTC
`val localDateTime = Clock.System.now().toLocalDateTime(TimeZone.of("UTC+5:30"))`
above code is not working I try to use +5:30 but work fine if I used +5. How can I fetch time for +5:30 GMT?

error I received:

> Uncaught Kotlin exception: kotlinx.datetime.IllegalTimeZoneException: Invalid ID for ZoneOffset, non numeric characters found: +5:30

**Comment by dkhalanskyjb** [comment] 2021-03-12 07:28
`UTC+05:30` should work (note the leading zero).

That said, a reminder is in order that using fixed-offset time zones is very rarely what one actually needs; instead, in the majority of cases, region-based time zones, like `TimeZone.of("Asia/Kolkata")` or `TimeZone.of("Asia/Colombo")`, should be used to make the code more reliable in case of future changes to the time zones.

**Comment by sshikalgar** [comment] 2021-03-12 07:37
Hi, @dkhalanskyjb

I have already tried for "Asia/Kolkata"

`val localDateTime = Clock.System.now().toLocalDateTime(TimeZone.currentSystemDefault())`

> Uncaught Kotlin exception: kotlinx.datetime.IllegalTimeZoneException: No timezone found with zone ID 'Asia/Kolkata'

**Comment by dkhalanskyjb** [comment] 2021-03-12 07:44
Huh, this is a bug. What platform does this happen on?

**Comment by sshikalgar** [comment] 2021-03-12 08:51
I am using Xcode 12.4 and Simulator to test iosApp project

**Comment by dkhalanskyjb** [comment] 2021-03-12 08:55
I see, thanks! This looks like a duplicate of https://github.com/Kotlin/kotlinx-datetime/issues/94, and if so, the issue is fixed in the current `master`. So, I would suggest either using the code from the `master` branch or sticking to the `+05:30` solution until the next release of our library.

**Comment by sshikalgar** [comment] 2021-03-12 08:59
> I see, thanks! This looks like a duplicate of #94, and if so, the issue is fixed in the current `master`. So, I would suggest either using the code from the `master` branch or sticking to the `+05:30` solution until the next release of our library.

`+05:30` also won't work as I have mentioned in my first comment.

**Comment by dkhalanskyjb** [comment] 2021-03-12 09:05
In the first comment, you talked about `+5:30`, not with `+05:30` (with the zero), right? `+05:30` should work.

**Comment by dkhalanskyjb** [comment] 2021-05-17 09:07
The `TimeZone.currentSystemDefault()` issue does not reproduce for me for 0.2.0. Feel free to reopen this issue if the problem persists!

**Closed by dkhalanskyjb** 2021-05-17 09:07 UTC

**Comment by vymarkov** [comment] 2025-02-01 23:00
Unfortunately, using a literal name for timezones like "Asia/Colombo" in the code leads to an `IllegalTimeZoneException` when targeting the JavaScript platform.

```kt
TimeZone.of("Asia/Colombo")
```

for IOS/Android platforms it works fine

**Comment by dkhalanskyjb** [comment] 2025-02-03 08:04
@vymarkov , please see https://github.com/Kotlin/kotlinx-datetime?tab=readme-ov-file#note-about-time-zones-in-js
