### ISSUE TITLE
set hours of LocalDateTime

### ISSUE THREAD

**Issue by periva101** [Kotlin/kotlinx-datetime#223] opened 2022-08-21 08:15 UTC
let's say that we have

val nowLocalDateTime = Clock.System.now()
    .toLocalDateTime(TimeZone.currentSystemDefault())
    
 I want to set the hours after getting the current LocalDateTime to 10 am .
  in java we used 
  
   val pickupCalendar =
            Calendar.getInstance().apply {
                add(Calendar.DATE, 2)
                this[Calendar.HOUR_OF_DAY] = 10
                this[Calendar.MINUTE] = 0
            }

**Comment by periva101** [comment] 2022-08-24 04:08
@svenjacobs thank you , they have to provide extension funs , on the instant for these use cases

**Comment by svenjacobs** [comment] 2022-08-24 09:51
`Instant` already provides a few functions and implements the `+` or `-` operator, for instance. See the sections [Instant arithmetic](https://github.com/Kotlin/kotlinx-datetime#instant-arithmetic) and [Date arithmetic](https://github.com/Kotlin/kotlinx-datetime#date-arithmetic). Everything should be there already. You just need to convert to `Instant` or `LocalDate` for intermediate steps.

**Comment by novotnyfra** [comment] 2022-09-05 10:02
@svenjacobs the issue is not about arithmetic operation (plus, minus), but setting to specific local value (e.g. set hours to 10AM). It cannot be done with `Instant ` as it is not dependent on zone.

**Comment by dkhalanskyjb** [comment] 2022-09-06 13:23
Yes, this is the way, though one must be wary of manipulating `LocalDateTime` even this way. For example, what should happen if clocks are moved from 9:30 to 10:30 that day, so the `LocalDateTime` with time `10:00` does not make sense in that time zone?

That said, we do consider adding such setter-like functions if we manage to make them both flexible and safe. Could you share your use case? Why do you need such code?

**Comment by xanscale** [comment] 2023-03-02 17:54
For Example actually change second and millisecond of an Instant is just INSANE!

```
        val instant: Instant = Clock.System.now()
        val localDateTime: LocalDateTime = instant.toLocalDateTime(TimeZone.currentSystemDefault())
        val localTime: LocalTime = localDateTime.time
        val localTime2: LocalTime = LocalTime(localTime.hour, localTime.minute, 0, 0)
        val newInstant: Instant = localDateTime.date.atTime(localTime2).toInstant(TimeZone.currentSystemDefault())


        val oldSyle = Calendar.getInstance().apply {
            set(Calendar.SECOND, 0)
            set(Calendar.MILLISECOND, 0)
        }
```

**Comment by dkhalanskyjb** [comment] 2023-03-27 10:58
Why do you need that? What's your high-level goal?

**Comment by xanscale** [comment] 2023-03-27 11:27
in my case i just need time slots of 1 hour from current time at start of hours, like

from "2023-03-27T11:23:33Z" i need to create

2023-03-27T11:00:00Z
2023-03-27T12:00:00Z
2023-03-27T13:00:00Z
2023-03-27T14:00:00Z

i think if there is "plusHours" there should be also "withHours" or somethink like that

**Comment by ilya-g** [comment] 2023-03-27 18:22
@xanscale Perhaps a function that truncates date/time to the specified unit would better fit your need? 
E.g. `Instant.truncateTo(DateTimeUnit, TZ)`

**Comment by xanscale** [comment] 2023-03-27 19:07
@ilya-g I suppose that withSecond is more generic

**Comment by dkhalanskyjb** [comment] 2023-12-01 13:49
Closing in favor of #325

**Closed by dkhalanskyjb** 2023-12-01 13:49 UTC
