### ISSUE TITLE
Instant parsing not working correctly on JS

### ISSUE THREAD

**Issue by jakubgwozdz** [Kotlin/kotlinx-datetime#67] opened 2020-11-03 22:33 UTC
Code like `"2019-10-28T14:00:00+01:00".toInstant()` works ok under JVM, but unfortunately not under JS.
This is caused by js-joda problem where `Instant` cannot use `+01:00` offsets (only `Z`works here) and causes
```
> var Instant = require("@js-joda/core").Instant;
undefined
> Instant.parse('2019-10-28T14:00:00+01:00')
Uncaught:
DateTimeParseException: Text '2019-10-28T14:00:00+01:00' could not be parsed at index 19: 2019-10-28T14:00:00+01:00, at index: 19
    at DateTimeFormatter._parseToBuilder (/Users/jakub.gwozdz/tmp/node_modules/@js-joda/core/dist/js-joda.js:6972:19)
    at DateTimeFormatter.parse2 (/Users/jakub.gwozdz/tmp/node_modules/@js-joda/core/dist/js-joda.js:6933:30)
    at DateTimeFormatter.parse (/Users/jakub.gwozdz/tmp/node_modules/@js-joda/core/dist/js-joda.js:6910:23)
    at Function.parse (/Users/jakub.gwozdz/tmp/node_modules/@js-joda/core/dist/js-joda.js:12368:46) {
  parsedString: [Function],
  errorIndex: [Function],
  toString: [Function]
}
```

solution would be going through ZonedDateTime:
```
> ZonedDateTime.parse('2019-10-28T14:00:00+01:00').toInstant()
Instant { _seconds: 1572267600, _nanos: 0 }
```

**Comment by ilya-g** [comment] 2020-11-09 00:12
Relates to #56.
I believe relying on `ZonedDateTime.parse` can allow more input strings than necessary, though a format can be used to limit allowed formats.

**Comment by jakubgwozdz** [comment] 2020-11-13 08:32
Well my use case is in using ktor-client->kotlinx.serialization (in multiplatform, js-browser included). And since the 3rd party rest api endpoint returns datetimes in `2019-10-28T14:00:00+01:00` ISO format, I cannot really use `Instant` class here.

**Comment by ilya-g** [comment] 2021-01-17 08:55
I'm closing this as a duplicate of #56 because essentially it's the same issue.

**Closed by ilya-g** 2021-01-17 08:55 UTC
Labels: duplicate
