### ISSUE TITLE
Desugaring in a library still fails with NoClassDefFoundError

### ISSUE THREAD

**Issue by desgraci** [Kotlin/kotlinx-datetime#207] opened 2022-05-24 11:13 UTC
When using:

```
import kotlinx.datetime.Instant

timestamp = Instant.fromEpochMilliseconds(timestamp)
```

I get:

```
2022-05-24 13:08:34.091 E: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Instant;
2022-05-24 13:08:34.091 E:     at kotlinx.datetime.Instant.<clinit>(Instant.kt:94)
...
2022-05-24 13:08:34.091 E:     at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
2022-05-24 13:08:34.092 E:     at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:166)
2022-05-24 13:08:34.092 E:     at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
...
2022-05-24 13:08:34.092 E:     at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
2022-05-24 13:08:34.092 E:     at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:166)
2022-05-24 13:08:34.092 E:     at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
...
2022-05-24 13:08:34.093 E:     at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:398)
2022-05-24 13:08:34.093 E:     at kotlinx.coroutines.flow.StateFlowImpl$collect$1.invokeSuspend(StateFlow.kt)
2022-05-24 13:08:34.093 E:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-05-24 13:08:34.093 E:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2022-05-24 13:08:34.093 E:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
2022-05-24 13:08:34.093 E:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
2022-05-24 13:08:34.093 E:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
2022-05-24 13:08:34.093 E:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
...
```

My gradle file contains:

```
plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
    id 'org.jetbrains.kotlin.plugin.serialization' version "$kotlin_version"
    id 'dagger.hilt.android.plugin'
    id 'maven-publish'
}
...
dependencies {
    ...
    implementation "org.jetbrains.kotlinx:kotlinx-datetime:0.3.3"
    ...
}

android {
...
compileOptions {
        coreLibraryDesugaringEnabled = true
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
...

}
```

EDIT:
Device is a SAMSUNG SM-T813 Android 7.0, API 24.

Same code works in other devices after API 26 as expected from the docs.

EDIT 2: 
I think this is related to transient limitations of the AAR, in theory it could be fixed adding de-sugaring (i.e. u need to bring all the java thing) into your implementing project :(

Why is this wrapper? java outside android? cannot be moved into the kotlin library or it is a ridiculous amount of work?

**Comment by ilya-g** [comment] 2022-05-25 01:45
The fact that the class name is still `Ljava/time/Instant;` indicates that the desugaring didn't happen. So it may be something wrong with your library desugaring setup. Have you followed the instructions from here? https://developer.android.com/studio/write/java8-support#library-desugaring

**Comment by desgraci** [comment] 2022-05-25 08:04
@ilya-g yes, I'm aware that the desugaring is not happening, that's what I'm reporting, and thanks for the link, I've already followed those steps when posting.

> I think this is related to transient limitations of the AAR, in theory it could be fixed adding de-sugaring (i.e. u need to bring all the java thing) into your implementing project :(

Thanks for the suggestion works, but this is the issue I'm reporting.

**Comment by tonymanou** [comment] 2022-06-08 16:02
@desgraci in https://github.com/Kotlin/kotlinx-datetime/issues/207#issuecomment-1136619163 **ilya-g** has a point: it is up to the final application module to enable core library desugaring if any of its dependencies are using newer Java API.
By the way, you may also want to specify this dependency in the app module:
```groovy
coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'
```

The problem you face is outside of the scope of **kotlinx-datetime**, unless the maintainers want to provide an implementation not using Java 8's Time API.

**Comment by dkhalanskyjb** [comment] 2022-07-14 11:37
We could probably implement this without Java 8's API fairly easily: we already have our own implementation in the Kotlin/Native part of the library. A good reason not to use our own implementation on the JVM is that the size of the jar archive would increase, which we would like to avoid.

In addition, the whole point of the whole desugaring mechanism is to allow for libraries that write code using the modern functionality from Java's library without having to consider Android separately. So, we're using the desugaring mechanism as intended.

I'm closing this issue for now, but feel free to reopen it if I'm missing something and there is a good reason to avoid desugaring. Then we'll have to consider ways to mitigate this.

**Closed by dkhalanskyjb** 2022-07-14 11:37 UTC
