### ISSUE TITLE
How to get current week of year?

### ISSUE THREAD

**Issue by chardskarth** [Kotlin/kotlinx-datetime#209] opened 2022-05-25 14:06 UTC
What's a counter part of the following code snippet?
```kotlin
Calendar.getInstance().get(Calendar.WEEK_OF_YEAR) // get current week of the year
```

**Comment by chardskarth** [comment] 2022-05-25 16:56
While waiting for a better solution, I'll settle with this **dirty, foul** workaround.

```kotlin
    constructor(): this(Unit.let{
        var now = Clock.System.now().toLocalDateTime(TimeZone.currentSystemDefault()).date
        val year = now.year
        var currentWeek = 0;
        while(now.year == year) {
            currentWeek++;
            now = now.minus(DateTimeUnit.WEEK)
        }
        currentWeek to year
    })
```

**Comment by dkhalanskyjb** [comment] 2022-05-27 10:05
Duplicate of https://github.com/Kotlin/kotlinx-datetime/issues/129

**Closed by dkhalanskyjb** 2022-05-27 10:05 UTC
