### ISSUE TITLE
InstantRange

### ISSUE THREAD

**Issue by mgroth0** [Kotlin/kotlinx-datetime#368] opened 2024-03-17 18:40 UTC
I am curious if it would be beneficial for this library to establish a standardized class encapsualting two instants.

I cannot currently think of a great name. `InstantRange` is accurate, but sounds strange. Other candidates are:

- TimePeriod
- Period
- InstantPeriod
- TImeRange

You get the picture.

The class would essentially be:

```kotlin
@Serializable
data class Period(val start: Instant, val end: Instant) {
    init { require(end > start) }
    val duration by lazy { end - start }
}
```

**Comment by dkhalanskyjb** [comment] 2024-03-18 07:39
Duplicate of https://github.com/Kotlin/kotlinx-datetime/issues/34
If you have specific use cases, please describe them there.

**Closed by dkhalanskyjb** 2024-03-18 07:39 UTC
