### ISSUE TITLE
Localization format

### ISSUE THREAD

**Issue by sonatard** [Kotlin/kotlinx-datetime#398] opened 2024-05-22 03:17 UTC
In Java, we can use DateTimeFormatter to select the appropriate format for each localization. Is there a way to achieve this with kotlinx-datetime?

https://docs.oracle.com/javase/jp/8/docs/api/java/time/format/DateTimeFormatter.html
https://developer.android.com/reference/java/time/format/FormatStyle

```kt
DateTimeFormatter.ofLocalizedDateTime(FormatStyle.SHORT)
// US
// 5/22/24 12:24 PM
// JP
// 2024/5/22 12:24

DateTimeFormatter.ofLocalizedDate(FormatStyle.SHORT)
// US
// 5/22/24
// JP
// 2024/5/22
```

**Comment by dkhalanskyjb** [comment] 2024-05-22 07:26
Duplicate of https://github.com/Kotlin/kotlinx-datetime/issues/352

**Closed by dkhalanskyjb** 2024-05-22 07:26 UTC
